// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogDocumentDataSlicesSlice = never;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Title field in *Blog*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Author field in *Blog*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<'blog_author'>;

  /**
   * Category field in *Blog*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<'blog_category'>;

  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Twitter Card Type field in *Blog*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.twitter_card_type
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  twitter_card_type: prismic.SelectField<'summary' | 'summary_large_image'>;

  /**
   * Canonical Url field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.canonical_url
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  canonical_url: prismic.KeyTextField;

  /**
   * Schema Org Data field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.schema_org_data
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  schema_org_data: prismic.RichTextField;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, 'blog', Lang>;

/**
 * Content for Blog Author documents
 */
interface BlogAuthorDocumentData {
  /**
   * Author field in *Blog Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_author.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Avatar field in *Blog Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_author.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;
}

/**
 * Blog Author document from Prismic
 *
 * - **API ID**: `blog_author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogAuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogAuthorDocumentData>,
    'blog_author',
    Lang
  >;

/**
 * Content for Blog Category documents
 */
interface BlogCategoryDocumentData {
  /**
   * Category field in *Blog Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_category.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;
}

/**
 * Blog Category document from Prismic
 *
 * - **API ID**: `blog_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogCategoryDocumentData>,
    'blog_category',
    Lang
  >;

type BlogListDocumentDataSlicesSlice = never;

/**
 * Content for Blog List documents
 */
interface BlogListDocumentData {
  /**
   * Badge field in *Blog List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_list.badge
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  badge: prismic.KeyTextField;

  /**
   * Title field in *Blog List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_list.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Featured Blog field in *Blog List*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_list.featured_blog
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featured_blog: prismic.ContentRelationshipField<'blog'>;

  /**
   * Slice Zone field in *Blog List*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_list.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogListDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_list.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_list.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_list.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Twitter Card Type field in *Blog List*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_list.twitter_card_type
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  twitter_card_type: prismic.SelectField<'summary' | 'summary_large_image'>;

  /**
   * Canonical Url field in *Blog List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_list.canonical_url
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  canonical_url: prismic.KeyTextField;

  /**
   * Schema Org Data field in *Blog List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_list.schema_org_data
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  schema_org_data: prismic.RichTextField;
}

/**
 * Blog List document from Prismic
 *
 * - **API ID**: `blog_list`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogListDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogListDocumentData>,
    'blog_list',
    Lang
  >;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    'navigation',
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | AboutUsSlice
  | FrequentlyAskedQuestionsSlice
  | ContactFormSlice
  | PricingSlice
  | PortfolioSlice
  | ProcessSlice
  | ServiceSlice
  | HeaderSlice
  | ProcessOverviewSlice
  | CallToActionSlice
  | HighlightSlice
  | FeaturesSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<'page'>;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * twitter_card_type field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.twitter_card_type
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  twitter_card_type: prismic.SelectField<'summary' | 'summary_large_image'>;

  /**
   * Canonical Url field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.canonical_url
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  canonical_url: prismic.KeyTextField;

  /**
   * Schema Org Data field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.schema_org_data
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  schema_org_data: prismic.RichTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;

  /**
   * Navigation Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  navigation_logo: prismic.ImageField<never>;

  /**
   * Privacy Policy field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.privacy_policy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  privacy_policy: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Terms of Service field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.terms_of_service
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  terms_of_service: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    'settings',
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | BlogAuthorDocument
  | BlogCategoryDocument
  | BlogListDocument
  | NavigationDocument
  | PageDocument
  | SettingsDocument;

/**
 * Item in *AboutUs → Left Background Color → Primary → IconsAndTexts*
 */
export interface AboutUsSliceLeftBackgroundColorPrimaryIconsandtextsItem {
  /**
   * Icon Title field in *AboutUs → Left Background Color → Primary → IconsAndTexts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.leftBackgroundColor.primary.iconsandtexts[].icon_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  icon_title: prismic.RichTextField;

  /**
   * Icon Description field in *AboutUs → Left Background Color → Primary → IconsAndTexts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.leftBackgroundColor.primary.iconsandtexts[].icon_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  icon_description: prismic.RichTextField;

  /**
   * Icons field in *AboutUs → Left Background Color → Primary → IconsAndTexts*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.leftBackgroundColor.primary.iconsandtexts[].icons
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icons: prismic.SelectField<'trendingUp' | 'gitMerge'>;
}

/**
 * Primary content in *AboutUs → Default → Primary*
 */
export interface AboutUsSliceDefaultPrimary {
  /**
   * Title field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Image field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Badge field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  badge: prismic.KeyTextField;

  /**
   * Description field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for AboutUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<AboutUsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *AboutUs → Left Background Color → Primary*
 */
export interface AboutUsSliceLeftBackgroundColorPrimary {
  /**
   * Title field in *AboutUs → Left Background Color → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.leftBackgroundColor.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Image field in *AboutUs → Left Background Color → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.leftBackgroundColor.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Badge field in *AboutUs → Left Background Color → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.leftBackgroundColor.primary.badge
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  badge: prismic.KeyTextField;

  /**
   * Description field in *AboutUs → Left Background Color → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.leftBackgroundColor.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button field in *AboutUs → Left Background Color → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.leftBackgroundColor.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * IconsAndTexts field in *AboutUs → Left Background Color → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.leftBackgroundColor.primary.iconsandtexts[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  iconsandtexts: prismic.GroupField<
    Simplify<AboutUsSliceLeftBackgroundColorPrimaryIconsandtextsItem>
  >;
}

/**
 * Left Background Color variation for AboutUs Slice
 *
 * - **API ID**: `leftBackgroundColor`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSliceLeftBackgroundColor = prismic.SharedSliceVariation<
  'leftBackgroundColor',
  Simplify<AboutUsSliceLeftBackgroundColorPrimary>,
  never
>;

/**
 * Slice variation for *AboutUs*
 */
type AboutUsSliceVariation =
  | AboutUsSliceDefault
  | AboutUsSliceLeftBackgroundColor;

/**
 * AboutUs Shared Slice
 *
 * - **API ID**: `about_us`
 * - **Description**: AboutUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSlice = prismic.SharedSlice<
  'about_us',
  AboutUsSliceVariation
>;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Title field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Use bold for highlighting
   * - **API ID Path**: call_to_action.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Background field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * Background Mobile field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.background_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_mobile: prismic.ImageField<never>;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CallToAction → CTA - Two Buttons → Primary*
 */
export interface CallToActionSliceCtaTwoButtonsPrimary {
  /**
   * Title field in *CallToAction → CTA - Two Buttons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Use bold for highlighting
   * - **API ID Path**: call_to_action.ctaTwoButtons.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CallToAction → CTA - Two Buttons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.ctaTwoButtons.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button field in *CallToAction → CTA - Two Buttons → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.ctaTwoButtons.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Background field in *CallToAction → CTA - Two Buttons → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.ctaTwoButtons.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * Background Mobile field in *CallToAction → CTA - Two Buttons → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.ctaTwoButtons.primary.background_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_mobile: prismic.ImageField<never>;

  /**
   * Outline Button field in *CallToAction → CTA - Two Buttons → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.ctaTwoButtons.primary.outline_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  outline_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * CTA - Two Buttons variation for CallToAction Slice
 *
 * - **API ID**: `ctaTwoButtons`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceCtaTwoButtons = prismic.SharedSliceVariation<
  'ctaTwoButtons',
  Simplify<CallToActionSliceCtaTwoButtonsPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation =
  | CallToActionSliceDefault
  | CallToActionSliceCtaTwoButtons;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  'call_to_action',
  CallToActionSliceVariation
>;

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Badge field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  badge: prismic.KeyTextField;

  /**
   * Text field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Terms Conditions field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.terms_conditions
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  terms_conditions: prismic.RichTextField;

  /**
   * Button field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  'contact_form',
  ContactFormSliceVariation
>;

/**
 * Item in *Features → Default → Primary → Features*
 */
export interface FeaturesSliceDefaultPrimaryFeaturesItem {
  /**
   * Image field in *Features → Default → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.features[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Features → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Features → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.features[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Features → Default → Primary*
 */
export interface FeaturesSliceDefaultPrimary {
  /**
   * badge field in *Features → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Services
   * - **API ID Path**: features.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  badge: prismic.KeyTextField;

  /**
   * Title field in *Features → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Features → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Features field in *Features → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<FeaturesSliceDefaultPrimaryFeaturesItem>
  >;

  /**
   * Button field in *Features → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FeaturesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation = FeaturesSliceDefault;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSlice = prismic.SharedSlice<
  'features',
  FeaturesSliceVariation
>;

/**
 * Item in *FrequentlyAskedQuestions → Default → Primary → FAQs*
 */
export interface FrequentlyAskedQuestionsSliceDefaultPrimaryFaqsItem {
  /**
   * Question field in *FrequentlyAskedQuestions → Default → Primary → FAQs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.default.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FrequentlyAskedQuestions → Default → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.default.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Item in *FrequentlyAskedQuestions → Centered → Primary → FAQs*
 */
export interface FrequentlyAskedQuestionsSliceCenteredPrimaryFaqsItem {
  /**
   * Question field in *FrequentlyAskedQuestions → Centered → Primary → FAQs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.centered.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FrequentlyAskedQuestions → Centered → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.centered.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *FrequentlyAskedQuestions → Default → Primary*
 */
export interface FrequentlyAskedQuestionsSliceDefaultPrimary {
  /**
   * Text field in *FrequentlyAskedQuestions → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * FAQs field in *FrequentlyAskedQuestions → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faqs: prismic.GroupField<
    Simplify<FrequentlyAskedQuestionsSliceDefaultPrimaryFaqsItem>
  >;
}

/**
 * Default variation for FrequentlyAskedQuestions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrequentlyAskedQuestionsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FrequentlyAskedQuestionsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *FrequentlyAskedQuestions → Centered → Primary*
 */
export interface FrequentlyAskedQuestionsSliceCenteredPrimary {
  /**
   * Text field in *FrequentlyAskedQuestions → Centered → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.centered.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * FAQs field in *FrequentlyAskedQuestions → Centered → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.centered.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faqs: prismic.GroupField<
    Simplify<FrequentlyAskedQuestionsSliceCenteredPrimaryFaqsItem>
  >;

  /**
   * Bottom Text field in *FrequentlyAskedQuestions → Centered → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.centered.primary.bottom_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text: prismic.RichTextField;

  /**
   * Button field in *FrequentlyAskedQuestions → Centered → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: frequently_asked_questions.centered.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Centered variation for FrequentlyAskedQuestions Slice
 *
 * - **API ID**: `centered`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrequentlyAskedQuestionsSliceCentered =
  prismic.SharedSliceVariation<
    'centered',
    Simplify<FrequentlyAskedQuestionsSliceCenteredPrimary>,
    never
  >;

/**
 * Slice variation for *FrequentlyAskedQuestions*
 */
type FrequentlyAskedQuestionsSliceVariation =
  | FrequentlyAskedQuestionsSliceDefault
  | FrequentlyAskedQuestionsSliceCentered;

/**
 * FrequentlyAskedQuestions Shared Slice
 *
 * - **API ID**: `frequently_asked_questions`
 * - **Description**: FrequentlyAskedQuestions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrequentlyAskedQuestionsSlice = prismic.SharedSlice<
  'frequently_asked_questions',
  FrequentlyAskedQuestionsSliceVariation
>;

/**
 * Item in *Header → PageHeaderNoBG → Primary → Badge Group*
 */
export interface HeaderSlicePageHeaderNoBgPrimaryBadgeGroupItem {
  /**
   * Badge Text field in *Header → PageHeaderNoBG → Primary → Badge Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pageHeaderNoBg.primary.badge_group[].badge_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  badge_text: prismic.KeyTextField;
}

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Page Header field in *Header → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.page_header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_header: prismic.RichTextField;

  /**
   * Page Sub header field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.page_sub_header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_sub_header: prismic.KeyTextField;

  /**
   * Header Button field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.header_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  header_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    'Primary' | 'Secondary'
  >;

  /**
   * Page Header Background field in *Header → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.page_header_background
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_header_background: prismic.RichTextField;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Header → PageHeader-no buttons → Primary*
 */
export interface HeaderSlicePageHeaderNoButtonsPrimary {
  /**
   * Page Header field in *Header → PageHeader-no buttons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pageHeaderNoButtons.primary.page_header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_header: prismic.RichTextField;

  /**
   * Page Sub header field in *Header → PageHeader-no buttons → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pageHeaderNoButtons.primary.page_sub_header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_sub_header: prismic.KeyTextField;

  /**
   * Page Header Background field in *Header → PageHeader-no buttons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pageHeaderNoButtons.primary.page_header_background
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_header_background: prismic.RichTextField;
}

/**
 * PageHeader-no buttons variation for Header Slice
 *
 * - **API ID**: `pageHeaderNoButtons`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlicePageHeaderNoButtons = prismic.SharedSliceVariation<
  'pageHeaderNoButtons',
  Simplify<HeaderSlicePageHeaderNoButtonsPrimary>,
  never
>;

/**
 * Primary content in *Header → PageHeaderNoBG → Primary*
 */
export interface HeaderSlicePageHeaderNoBgPrimary {
  /**
   * Page Header field in *Header → PageHeaderNoBG → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pageHeaderNoBg.primary.page_header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_header: prismic.RichTextField;

  /**
   * Page Sub header field in *Header → PageHeaderNoBG → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pageHeaderNoBg.primary.page_sub_header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_sub_header: prismic.KeyTextField;

  /**
   * Page Header Background field in *Header → PageHeaderNoBG → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pageHeaderNoBg.primary.page_header_background
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_header_background: prismic.RichTextField;

  /**
   * Badge Group field in *Header → PageHeaderNoBG → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pageHeaderNoBg.primary.badge_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  badge_group: prismic.GroupField<
    Simplify<HeaderSlicePageHeaderNoBgPrimaryBadgeGroupItem>
  >;
}

/**
 * PageHeaderNoBG variation for Header Slice
 *
 * - **API ID**: `pageHeaderNoBg`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlicePageHeaderNoBg = prismic.SharedSliceVariation<
  'pageHeaderNoBg',
  Simplify<HeaderSlicePageHeaderNoBgPrimary>,
  never
>;

/**
 * Primary content in *Header → Page Header-Two Shadows → Primary*
 */
export interface HeaderSlicePageHeaderTwoShadowsPrimary {
  /**
   * Page Header field in *Header → Page Header-Two Shadows → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pageHeaderTwoShadows.primary.page_header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_header: prismic.RichTextField;

  /**
   * Page Sub header field in *Header → Page Header-Two Shadows → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pageHeaderTwoShadows.primary.page_sub_header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_sub_header: prismic.KeyTextField;

  /**
   * Header Button field in *Header → Page Header-Two Shadows → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pageHeaderTwoShadows.primary.header_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  header_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    'Primary' | 'Secondary'
  >;

  /**
   * Page Header Background field in *Header → Page Header-Two Shadows → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pageHeaderTwoShadows.primary.page_header_background
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_header_background: prismic.RichTextField;
}

/**
 * Page Header-Two Shadows variation for Header Slice
 *
 * - **API ID**: `pageHeaderTwoShadows`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlicePageHeaderTwoShadows = prismic.SharedSliceVariation<
  'pageHeaderTwoShadows',
  Simplify<HeaderSlicePageHeaderTwoShadowsPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation =
  | HeaderSliceDefault
  | HeaderSlicePageHeaderNoButtons
  | HeaderSlicePageHeaderNoBg
  | HeaderSlicePageHeaderTwoShadows;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<'header', HeaderSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Images*
 */
export interface HeroSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *Hero → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Use bold to turn it to yellow
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Images field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Item in *Highlight → Default → Primary → Highlight*
 */
export interface HighlightSliceDefaultPrimaryHighlightItem {
  /**
   * Title field in *Highlight → Default → Primary → Highlight*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Use bold for highlighting
   * - **API ID Path**: highlight.default.primary.highlight[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Highlight → Default → Primary → Highlight*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.default.primary.highlight[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Highlight → Default → Primary*
 */
export interface HighlightSliceDefaultPrimary {
  /**
   * Image field in *Highlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Highlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Use bold for highlighting
   * - **API ID Path**: highlight.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Highlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Highlight field in *Highlight → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.default.primary.highlight[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  highlight: prismic.GroupField<
    Simplify<HighlightSliceDefaultPrimaryHighlightItem>
  >;
}

/**
 * Default variation for Highlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HighlightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Highlight*
 */
type HighlightSliceVariation = HighlightSliceDefault;

/**
 * Highlight Shared Slice
 *
 * - **API ID**: `highlight`
 * - **Description**: Highlight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSlice = prismic.SharedSlice<
  'highlight',
  HighlightSliceVariation
>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image → Banner → Primary*
 */
export interface ImageSliceBannerPrimary {
  /**
   * Image field in *Image → Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.banner.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Banner variation for Image Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceBanner = prismic.SharedSliceVariation<
  'banner',
  Simplify<ImageSliceBannerPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceBanner;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<'image', ImageSliceVariation>;

/**
 * Item in *ImageCards → Default → Primary → Cards*
 */
export interface ImageCardsSliceDefaultPrimaryCardsItem {
  /**
   * Image field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;
}

/**
 * Primary content in *ImageCards → Default → Primary*
 */
export interface ImageCardsSliceDefaultPrimary {
  /**
   * Heading field in *ImageCards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Cards field in *ImageCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<ImageCardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for ImageCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ImageCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageCards*
 */
type ImageCardsSliceVariation = ImageCardsSliceDefault;

/**
 * ImageCards Shared Slice
 *
 * - **API ID**: `image_cards`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSlice = prismic.SharedSlice<
  'image_cards',
  ImageCardsSliceVariation
>;

/**
 * Item in *Portfolio → Default → Primary → Project*
 */
export interface PortfolioSliceDefaultPrimaryProjectItem {
  /**
   * Image field in *Portfolio → Default → Primary → Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.project[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *Portfolio → Default → Primary → Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.project[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Shadow Color field in *Portfolio → Default → Primary → Project*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.project[].shadow_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  shadow_color: prismic.ColorField;
}

/**
 * Primary content in *Portfolio → Default → Primary*
 */
export interface PortfolioSliceDefaultPrimary {
  /**
   * Badge field in *Portfolio → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  badge: prismic.KeyTextField;

  /**
   * Title field in *Portfolio → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Portfolio → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Project field in *Portfolio → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.project[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  project: prismic.GroupField<
    Simplify<PortfolioSliceDefaultPrimaryProjectItem>
  >;
}

/**
 * Default variation for Portfolio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<PortfolioSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Portfolio*
 */
type PortfolioSliceVariation = PortfolioSliceDefault;

/**
 * Portfolio Shared Slice
 *
 * - **API ID**: `portfolio`
 * - **Description**: Portfolio
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioSlice = prismic.SharedSlice<
  'portfolio',
  PortfolioSliceVariation
>;

/**
 * Item in *Pricing → Default → Primary → Features*
 */
export interface PricingSliceDefaultPrimaryFeaturesItem {
  /**
   * Icon field in *Pricing → Default → Primary → Features*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    'alignStartVertical' | 'monitor' | 'messagesSquare'
  >;

  /**
   * Text field in *Pricing → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.features[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Item in *Pricing → Default → Primary → Inclusions*
 */
export interface PricingSliceDefaultPrimaryInclusionsItem {
  /**
   * Text field in *Pricing → Default → Primary → Inclusions*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.inclusions[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *Pricing → Default → Primary*
 */
export interface PricingSliceDefaultPrimary {
  /**
   * Title field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Features field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<PricingSliceDefaultPrimaryFeaturesItem>
  >;

  /**
   * Price Text field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.price_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  price_text: prismic.RichTextField;

  /**
   * Price field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.price
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  price: prismic.RichTextField;

  /**
   * Inclusions field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.inclusions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  inclusions: prismic.GroupField<
    Simplify<PricingSliceDefaultPrimaryInclusionsItem>
  >;

  /**
   * Button field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Pricing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<PricingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Pricing*
 */
type PricingSliceVariation = PricingSliceDefault;

/**
 * Pricing Shared Slice
 *
 * - **API ID**: `pricing`
 * - **Description**: Pricing
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSlice = prismic.SharedSlice<
  'pricing',
  PricingSliceVariation
>;

/**
 * Item in *Process → Default → Primary → Steps*
 */
export interface ProcessSliceDefaultPrimaryStepsItem {
  /**
   * Icon field in *Process → Default → Primary → Steps*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.steps[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    'messageCircleMore' | 'penTool' | 'code2' | 'rocket'
  >;

  /**
   * Text field in *Process → Default → Primary → Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.steps[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Subtext field in *Process → Default → Primary → Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.steps[].subtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtext: prismic.RichTextField;
}

/**
 * Primary content in *Process → Default → Primary*
 */
export interface ProcessSliceDefaultPrimary {
  /**
   * Badge field in *Process → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  badge: prismic.KeyTextField;

  /**
   * Title field in *Process → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Process → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Process → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Steps field in *Process → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  steps: prismic.GroupField<Simplify<ProcessSliceDefaultPrimaryStepsItem>>;
}

/**
 * Default variation for Process Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ProcessSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Process*
 */
type ProcessSliceVariation = ProcessSliceDefault;

/**
 * Process Shared Slice
 *
 * - **API ID**: `process`
 * - **Description**: Process
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessSlice = prismic.SharedSlice<
  'process',
  ProcessSliceVariation
>;

/**
 * Item in *ProcessOverview → Default → Primary → Process*
 */
export interface ProcessOverviewSliceDefaultPrimaryProcessItem {
  /**
   * Icon field in *ProcessOverview → Default → Primary → Process*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: process_overview.default.primary.process[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<'lightbulb' | 'pencil' | 'box'>;

  /**
   * Title field in *ProcessOverview → Default → Primary → Process*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_overview.default.primary.process[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ProcessOverview → Default → Primary → Process*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_overview.default.primary.process[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ProcessOverview → Default → Primary*
 */
export interface ProcessOverviewSliceDefaultPrimary {
  /**
   * Title field in *ProcessOverview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_overview.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Process field in *ProcessOverview → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: process_overview.default.primary.process[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  process: prismic.GroupField<
    Simplify<ProcessOverviewSliceDefaultPrimaryProcessItem>
  >;
}

/**
 * Default variation for ProcessOverview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessOverviewSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ProcessOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProcessOverview*
 */
type ProcessOverviewSliceVariation = ProcessOverviewSliceDefault;

/**
 * ProcessOverview Shared Slice
 *
 * - **API ID**: `process_overview`
 * - **Description**: ProcessOverview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessOverviewSlice = prismic.SharedSlice<
  'process_overview',
  ProcessOverviewSliceVariation
>;

/**
 * Item in *Service → Left Image 1 → Primary → Items*
 */
export interface ServiceSliceDefaultPrimaryItemsItem {
  /**
   * Icon field in *Service → Left Image 1 → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: service.default.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<'settings' | 'monitorsmartphone' | 'search'>;

  /**
   * Text field in *Service → Left Image 1 → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.default.primary.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *Service → Left Image 1 → Primary*
 */
export interface ServiceSliceDefaultPrimary {
  /**
   * Badge field in *Service → Left Image 1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  badge: prismic.KeyTextField;

  /**
   * Image field in *Service → Left Image 1 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Service → Left Image 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Service → Left Image 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Items field in *Service → Left Image 1 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<ServiceSliceDefaultPrimaryItemsItem>>;

  /**
   * Button field in *Service → Left Image 1 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Left Image 1 variation for Service Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ServiceSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Service → Right Image 1 → Primary*
 */
export interface ServiceSliceRightImage1Primary {
  /**
   * Badge field in *Service → Right Image 1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.rightImage1.primary.badge
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  badge: prismic.KeyTextField;

  /**
   * Image field in *Service → Right Image 1 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.rightImage1.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Service → Right Image 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.rightImage1.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Service → Right Image 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.rightImage1.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button field in *Service → Right Image 1 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service.rightImage1.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Right Image 1 variation for Service Slice
 *
 * - **API ID**: `rightImage1`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSliceRightImage1 = prismic.SharedSliceVariation<
  'rightImage1',
  Simplify<ServiceSliceRightImage1Primary>,
  never
>;

/**
 * Primary content in *Service → Left Image 2 → Primary*
 */
export interface ServiceSliceLeftImage2Primary {
  /**
   * Badge field in *Service → Left Image 2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.leftImage2.primary.badge
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  badge: prismic.KeyTextField;

  /**
   * Image field in *Service → Left Image 2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.leftImage2.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Service → Left Image 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.leftImage2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Service → Left Image 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.leftImage2.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button field in *Service → Left Image 2 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service.leftImage2.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Left Image 2 variation for Service Slice
 *
 * - **API ID**: `leftImage2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSliceLeftImage2 = prismic.SharedSliceVariation<
  'leftImage2',
  Simplify<ServiceSliceLeftImage2Primary>,
  never
>;

/**
 * Slice variation for *Service*
 */
type ServiceSliceVariation =
  | ServiceSliceDefault
  | ServiceSliceRightImage1
  | ServiceSliceLeftImage2;

/**
 * Service Shared Slice
 *
 * - **API ID**: `service`
 * - **Description**: Service
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSlice = prismic.SharedSlice<
  'service',
  ServiceSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogAuthorDocument,
      BlogAuthorDocumentData,
      BlogCategoryDocument,
      BlogCategoryDocumentData,
      BlogListDocument,
      BlogListDocumentData,
      BlogListDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      AboutUsSlice,
      AboutUsSliceDefaultPrimary,
      AboutUsSliceLeftBackgroundColorPrimaryIconsandtextsItem,
      AboutUsSliceLeftBackgroundColorPrimary,
      AboutUsSliceVariation,
      AboutUsSliceDefault,
      AboutUsSliceLeftBackgroundColor,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceCtaTwoButtonsPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceCtaTwoButtons,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      FeaturesSlice,
      FeaturesSliceDefaultPrimaryFeaturesItem,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceVariation,
      FeaturesSliceDefault,
      FrequentlyAskedQuestionsSlice,
      FrequentlyAskedQuestionsSliceDefaultPrimaryFaqsItem,
      FrequentlyAskedQuestionsSliceDefaultPrimary,
      FrequentlyAskedQuestionsSliceCenteredPrimaryFaqsItem,
      FrequentlyAskedQuestionsSliceCenteredPrimary,
      FrequentlyAskedQuestionsSliceVariation,
      FrequentlyAskedQuestionsSliceDefault,
      FrequentlyAskedQuestionsSliceCentered,
      HeaderSlice,
      HeaderSliceDefaultPrimary,
      HeaderSlicePageHeaderNoButtonsPrimary,
      HeaderSlicePageHeaderNoBgPrimaryBadgeGroupItem,
      HeaderSlicePageHeaderNoBgPrimary,
      HeaderSlicePageHeaderTwoShadowsPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeaderSlicePageHeaderNoButtons,
      HeaderSlicePageHeaderNoBg,
      HeaderSlicePageHeaderTwoShadows,
      HeroSlice,
      HeroSliceDefaultPrimaryImagesItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HighlightSlice,
      HighlightSliceDefaultPrimaryHighlightItem,
      HighlightSliceDefaultPrimary,
      HighlightSliceVariation,
      HighlightSliceDefault,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceBannerPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceBanner,
      ImageCardsSlice,
      ImageCardsSliceDefaultPrimaryCardsItem,
      ImageCardsSliceDefaultPrimary,
      ImageCardsSliceVariation,
      ImageCardsSliceDefault,
      PortfolioSlice,
      PortfolioSliceDefaultPrimaryProjectItem,
      PortfolioSliceDefaultPrimary,
      PortfolioSliceVariation,
      PortfolioSliceDefault,
      PricingSlice,
      PricingSliceDefaultPrimaryFeaturesItem,
      PricingSliceDefaultPrimaryInclusionsItem,
      PricingSliceDefaultPrimary,
      PricingSliceVariation,
      PricingSliceDefault,
      ProcessSlice,
      ProcessSliceDefaultPrimaryStepsItem,
      ProcessSliceDefaultPrimary,
      ProcessSliceVariation,
      ProcessSliceDefault,
      ProcessOverviewSlice,
      ProcessOverviewSliceDefaultPrimaryProcessItem,
      ProcessOverviewSliceDefaultPrimary,
      ProcessOverviewSliceVariation,
      ProcessOverviewSliceDefault,
      ServiceSlice,
      ServiceSliceDefaultPrimaryItemsItem,
      ServiceSliceDefaultPrimary,
      ServiceSliceRightImage1Primary,
      ServiceSliceLeftImage2Primary,
      ServiceSliceVariation,
      ServiceSliceDefault,
      ServiceSliceRightImage1,
      ServiceSliceLeftImage2
    };
  }
}
