// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  about_us: dynamic(() => import('./AboutUs')),
  call_to_action: dynamic(() => import('./CallToAction')),
  contact_form: dynamic(() => import('./ContactForm')),
  features: dynamic(() => import('./Features')),
  frequently_asked_questions: dynamic(
    () => import('./FrequentlyAskedQuestions')
  ),
  header: dynamic(() => import('./Header')),
  hero: dynamic(() => import('./Hero')),
  highlight: dynamic(() => import('./Highlight')),
  portfolio: dynamic(() => import('./Portfolio')),
  pricing: dynamic(() => import('./Pricing')),
  process: dynamic(() => import('./Process')),
  process_overview: dynamic(() => import('./ProcessOverview')),
  service: dynamic(() => import('./Service'))
};
